### ISSUE TITLE
Problem with booting sidekiq 

### ISSUE THREAD

**Issue by parallela** [COVID-19-Bulgaria/covid-scraper#1]
### System information: 
- Windows 10 Pro
- Ruby Version: `ruby 2.6.6p146 (2020-03-31 revision 67876) [x64-mingw32]`
- Redis Version: `redis-2.4.5`

**Issue:** When i run both of it (sidekiq and sidekiq-web) i get that error message: [sidekiq.log](https://github.com/COVID-19-Bulgaria/covid-scraper/files/4464427/sidekiq.log)

** Files: **
`GemFile`: [GEMFILE.txt](https://github.com/COVID-19-Bulgaria/covid-scraper/files/4464432/GEMFILE.txt)
`Redis config`: [redis_config.txt](https://github.com/COVID-19-Bulgaria/covid-scraper/files/4464434/redis_config.txt)

I did all of the things from the readme file. (Setup .env file etc..)

**Notice:**
I can't use docker right now because i have limited source on my computer until 20/05/2020

**Comment by veskoy** [comment]
Unfortunately I don't have a Windows environment to reproduce the issue.
For that reason only UNIX environments will be supported.
